# Generated by Django 4.2.23 on 2025-11-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_reset_token_user_reset_token_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('captain', 'Captain')], default='user', max_length=20),
        ),
    ]
