# Generated by Django 5.2.1 on 2026-02-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_is_online_user_rating_user_total_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhaar_image',
            field=models.ImageField(blank=True, null=True, upload_to='documents/aadhaar/'),
        ),
        migrations.AddField(
            model_name='user',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='documents_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='food_license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pan_image',
            field=models.ImageField(blank=True, null=True, upload_to='documents/pan/'),
        ),
        migrations.AddField(
            model_name='user',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
