# Generated by Django 5.2.1 on 2026-03-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_aadhaar_image_user_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('chef', 'Chef'), ('captain', 'Captain')], max_length=20, null=True),
        ),
    ]
