# Generated by Django 4.2.23 on 2025-09-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_deliveryaddress_latitude_deliveryaddress_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
