# Generated by Django 5.2.1 on 2026-02-27 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_deliveryaddress_full_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_captain',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'captain'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_chef',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'chef'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chef_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('preparing', 'Preparing'), ('ready_for_pickup', 'Ready for Pickup'), ('assigned', 'Assigned'), ('picked_up', 'Picked Up'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
    ]
