# Generated by Django 5.2.1 on 2026-04-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_assigned_captain_order_assigned_chef_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=6),
        ),
    ]
