# Generated by Django 5.2.1 on 2026-07-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
