# Generated by Django 4.2.23 on 2025-09-29 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_supportticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='food_item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
